// Generated by CoffeeScript 1.7.1
(function() {
  var $, baseFolder, root, rootUrl;

  root = typeof window !== "undefined" && window !== null ? window : global;

  $ = root.jQuery;

  root.template = function(id) {
    return Handlebars.compile($('#' + id).html());
  };

  root.removeTrailingSlash = function(route) {
    var index;
    index = route.length - 1;
    if (route.charAt(index) === '/') {
      return route = route.substring(0, index);
    } else {
      return route;
    }
  };

  baseFolder = window.location.pathname.replace('/', '').split('/')[0];

  rootUrl = window.location.protocol + "//" + window.location.host + "/" + baseFolder;

  $.ajaxPrefilter(function(options) {
    options.url = rootUrl + options.url;
    return false;
  });

  root.Otalvaro = (function() {
    function Otalvaro() {}

    Otalvaro.Models = {};

    Otalvaro.Collections = {};

    Otalvaro.Views = {};

    Otalvaro.Routers = {};

    return Otalvaro;

  })();

}).call(this);

//# sourceMappingURL=init.map
