// Generated by CoffeeScript 1.7.1
(function() {
  var Otalvaro, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Otalvaro = root.Otalvaro;

  Otalvaro.Views.Blog = (function(_super) {
    __extends(Blog, _super);

    function Blog() {
      this.alert = __bind(this.alert, this);
      return Blog.__super__.constructor.apply(this, arguments);
    }

    Blog.prototype.template = root.template('blogTemplate');

    Blog.prototype.initialize = function(options) {
      return this.itemView = options.itemView;
    };

    Blog.prototype.setView = function(mainLayOutCallback) {
      this.mainLayOutCallback = mainLayOutCallback;
      this.itemView.setView(this.alert);
      return this;
    };

    Blog.prototype.alert = function(renderedView) {
      var header, navi, nodeFragment;
      header = $('<h2 class="navCrumb bioCrumb">Blog<i class="fa fa-book"></i></h2>');
      navi = $(' <ul id="newsNavi" class="pageNavi"> <li class="navBtns selectedNav">1</li> <li class="navBtns">2</li> <li class="navBtns">3</li> <li class="navBtns">4</li> </ul>');
      nodeFragment = $(document.createDocumentFragment());
      nodeFragment.append(header).append(renderedView).append(navi);
      console.log(nodeFragment);
      return this.mainLayOutCallback(nodeFragment);

      /*html = '<h2 class="navCrumb bioCrumb">Blog
                  <i class="fa fa-book"></i>
              </h2>'
       */
    };

    Blog.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return Blog;

  })(Otalvaro.Views.BaseContent);

  Otalvaro.Views.BlogCollection = (function(_super) {
    __extends(BlogCollection, _super);

    function BlogCollection() {
      return BlogCollection.__super__.constructor.apply(this, arguments);
    }

    BlogCollection.prototype.tagName = 'ul';

    BlogCollection.prototype.id = 'blogFeed';

    BlogCollection.prototype.className = 'feed';

    return BlogCollection;

  })(Otalvaro.Views.CollectionView);

  Otalvaro.Views.BlogEntry = (function(_super) {
    __extends(BlogEntry, _super);

    function BlogEntry() {
      this.showFullEntry = __bind(this.showFullEntry, this);
      return BlogEntry.__super__.constructor.apply(this, arguments);
    }

    BlogEntry.prototype.tagName = 'li';

    BlogEntry.prototype.className = 'grid entryFeed';

    BlogEntry.prototype.initialize = function() {
      return this.template = template('blogEntryTemplate');
    };

    BlogEntry.prototype.events = {
      'click': 'showFullEntry'
    };

    BlogEntry.prototype.showFullEntry = function(e) {
      var $newsWrapper, fullNews;
      e.preventDefault();
      e.stopPropagation();
      fullNews = new Otalvaro.Views.fullNews({
        model: this.model
      });
      $newsWrapper = $(this.$el.closest('.newsContentWrapper'));
      $newsWrapper.html(fullNews.render(renderedView).el);
      return null;
    };

    BlogEntry.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return BlogEntry;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=blog.map
