// Generated by CoffeeScript 1.7.1
(function() {
  var Otalvaro, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Otalvaro = root.Otalvaro;

  Otalvaro.Views.Home = (function(_super) {
    __extends(Home, _super);

    function Home() {
      return Home.__super__.constructor.apply(this, arguments);
    }

    Home.prototype.template = root.template('homeTemplate');

    Home.prototype.fetchModel = function(callback) {
      this.model.fetch({
        success: (function(_this) {
          return function() {
            _this.render(callback);
            root.twttr.widgets.load();
            return _this;
          };
        })(this),
        error: function(collection, response) {
          return console.log('Error while fetching the model', response);
        }
      });
      return this;
    };

    return Home;

  })(Otalvaro.Views.BaseContent);

}).call(this);

//# sourceMappingURL=home.map
