// Generated by CoffeeScript 1.7.1
(function() {
  var Otalvaro, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Otalvaro = root.Otalvaro;

  Otalvaro.Views.MainLayOut = (function(_super) {
    __extends(MainLayOut, _super);

    function MainLayOut() {
      return MainLayOut.__super__.constructor.apply(this, arguments);
    }

    MainLayOut.prototype.el = '#mainContent';

    MainLayOut.prototype.initialize = function() {
      return this.firstLoad = true;
    };

    MainLayOut.prototype.update = function(view) {
      if (!this.firstLoad) {
        this.$el.removeClass('fastFadeIn').addClass('fastFadeOut').empty();
        return view = view.setView((function(_this) {
          return function(renderedView) {
            return _this.render(renderedView);
          };
        })(this));
      } else {
        return this.firstLoad = false;
      }
    };

    MainLayOut.prototype.render = function(view) {
      this.$el.removeClass('fastFadeOut').addClass('fastFadeIn').append(view);
      return this;
    };

    return MainLayOut;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=main-layout.map
