// Generated by CoffeeScript 1.7.1
(function() {
  var Otalvaro, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof window !== "undefined" && window !== null ? window : global;

  Otalvaro = root.Otalvaro;

  Otalvaro.Routers.Router = (function(_super) {
    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      '(/)': 'home',
      'biografia(/)': 'bio',
      'blog(/)': 'blog',
      'fotos(/)': 'gallery'
    };

    Router.prototype.initialize = function() {
      var baseFolder, bioModel, blogCollection, blogCollectionView, galleryModel, homeModel;
      this.mainNav = new Otalvaro.Views.navigation;
      this.sliderCover = new Otalvaro.Views.SliderCover;
      this.mainLayout = new Otalvaro.Views.MainLayOut;
      homeModel = new Otalvaro.Models.Home;
      this.homeView = new Otalvaro.Views.Home({
        model: homeModel
      });
      bioModel = new Otalvaro.Models.Bio;
      this.bioView = new Otalvaro.Views.Bio({
        model: bioModel
      });
      blogCollection = new Otalvaro.Collections.Blog;
      blogCollectionView = new Otalvaro.Views.BlogCollection({
        itemViewClass: Otalvaro.Views.BlogEntry,
        collection: blogCollection
      });
      this.blogView = new Otalvaro.Views.Blog({
        itemView: blogCollectionView
      });
      galleryModel = new Otalvaro.Models.Gallery;
      this.galleryView = new Otalvaro.Views.Gallery({
        model: galleryModel
      });
      baseFolder = window.location.pathname.replace('/', '').split('/')[0];
      return Backbone.history.start({
        pushState: true,
        root: baseFolder
      });
    };

    Router.prototype.getCurrentRoute = function() {
      var currentRoute;
      currentRoute = root.removeTrailingSlash(Backbone.history.fragment);
      return currentRoute;
    };

    Router.prototype.updateNav = function(route) {
      if (route == null) {
        route = this.getCurrentRoute();
      }
      return this.mainNav.findCurrentRoute(route);
    };

    Router.prototype.home = function() {
      this.sliderCover.expand();
      this.mainLayout.update(this.homeView);
      return null;
    };

    Router.prototype.bio = function() {
      this.sliderCover.collapse();
      return this.mainLayout.update(this.bioView);
    };

    Router.prototype.blog = function() {
      this.sliderCover.collapse();
      return this.mainLayout.update(this.blogView);
    };

    Router.prototype.gallery = function() {
      this.sliderCover.collapse();
      return this.mainLayout.update(this.galleryView);
    };

    Router.prototype.page = function() {
      return this.sliderCover.collapse();
    };

    return Router;

  })(Backbone.Router);

  $(function() {
    root.app = new Otalvaro.Routers.Router();
    return root.app.updateNav();
  });

}).call(this);

//# sourceMappingURL=app.map
